remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

#theme: jekyll-theme-slate
#remote_theme: mmistakes/minimal-mistakes

title: HuPKit
description: Project maintainance tool for GitHub repositories
